name       : perl-test-needs
version    : 0.002005
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Test-Needs-0.002005.tar.gz : 5a4f33983586edacdbe00a3b429a9834190140190dab28d0f873c394eb7df399
license    : Artistic-1.0
component  : programming.perl
summary    : Test::Needs - Skip tests when modules not available
description: |
    Skip test scripts if modules are not available. The requested modules will be loaded, and optionally have their versions checked. If the module is missing, the test script will be skipped. Modules that are found but fail to compile will exit with an error rather than skip.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
